spring:
  datasource:
    url: jdbc:postgresql://localhost/call_center
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

liquibase:
  change-log: classpath:db/master.xml
